/* Bootstrap Recommended Media Queries
Small devices (landscape phones, 576px and up)
    @media (min-width: 576px) { ... }
Medium devices (tablets, 768px and up)
    @media (min-width: 768px) { ... }
Large devices (desktops, 992px and up)
    @media (min-width: 992px) { ... }
X-Large devices (large desktops, 1200px and up)
    @media (min-width: 1200px) { ... }
XX-Large devices (larger desktops, 1400px and up)
    @media (min-width: 1400px) { ... }

This is an what the iframe generated by Etsy.Mini looks like. By wrapping the Etsy Mini
<script> tags in a <div> with a custom id, you can find this iframe and update its styling.

<iframe frameborder="0" src="https://www.etsy.com/mini.php?shop_id=9999999&amp;image_type=gallery&amp;rows=5&amp;columns=5&amp;featured=0" width="975" height="1025"></iframe> 
*/

(() => {
    window.addEventListener('load', () => {
        startMediaQueries();
    })
})();

function startMediaQueries() {
    let setEtsyMiniSize = (etsyMini) => {
        etsyMini.mediaQuery.addEventListener("change", event => {
            if (event.matches) {
                let etsyIframe = document.getElementById("etsy-iframe-container")
                    .getElementsByTagName("iframe");
                let etsyURL = new URL(etsyIframe[0].src);
                etsyURL.searchParams.set("rows", etsyMini.rows);
                etsyURL.searchParams.set("columns", etsyMini.columns);
                etsyIframe[0].src = etsyURL.toString();
            }
        });
    }

    const etsyMiniSizes = [
        { rows: "5", columns: "2", mediaQuery: window.matchMedia("(min-width: 576px)") },
        { rows: "5", columns: "2", mediaQuery: window.matchMedia("(max-width: 576px)") },
        { rows: "5", columns: "2", mediaQuery: window.matchMedia("(min-width: 576px) and (max-width: 767px) ") },
        { rows: "5", columns: "2", mediaQuery: window.matchMedia("(min-width: 768px)") },
        { rows: "5", columns: "2", mediaQuery: window.matchMedia("(min-width: 768px) and (max-width: 991px)") },
        { rows: "5", columns: "5", mediaQuery: window.matchMedia("(min-width: 992px)") },
        { rows: "5", columns: "5", mediaQuery: window.matchMedia("(max-width: 992px)") },
        { rows: "5", columns: "5", mediaQuery: window.matchMedia("(min-width: 1200px)") },
        { rows: "5", columns: "5", mediaQuery: window.matchMedia("(min-width: 1400px)") },
        { rows: "5", columns: "5", mediaQuery: window.matchMedia("(min-width: 992px) and (max-width: 1200px)") },

    ];

    etsyMiniSizes.map(setEtsyMiniSize);
}

startMediaQueries();